#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-cscope \
    --enable-multibyte \
    --with-ex-name=vim-ex \
    --with-view-name=vim-view \
    --with-features=huge \
    --enable-perlinterp=yes \
#    --enable-pythoninterp=yes \ # meh trash
    --enable-python3interp=yes \
    --with-python3-config-dir=$(python3-config --configdir) \
    --enable-rubyinterp=yes \
    --enable-luainterp=yes \
    --disable-netbeans \
    --disable-gpm \
    --disable-hangulinput \
    --disable-xim \
    --enable-gui=gtk2 \
    --disable-nls \
    --without-x

make
make DESTDIR="$1" install
